#############################################################################
# Makefile for building: ../bin/release/IKUNPlayer.app/Contents/MacOS/IKUNPlayer
# Generated by qmake (3.1) (Qt 5.15.5)
# Project:  IKUNPlayer.pro
# Template: app
# Command: /Users/zx/qt5.15/qt5.15/bin/qmake -o Makefile IKUNPlayer.pro -spec macx-clang CONFIG+=release CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -Impv/include -I../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers -I../../../qt5.15/qt5.15/lib/QtGui.framework/Headers -I../../../qt5.15/qt5.15/lib/QtQml.framework/Headers -I../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers -I../../../qt5.15/qt5.15/lib/QtCore.framework/Headers -I../build/release/moc -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I../build/release/ui -I../../../qt5.15/qt5.15/mkspecs/macx-clang -F/Users/zx/qt5.15/qt5.15/lib
QMAKE         = /Users/zx/qt5.15/qt5.15/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/zx/qt5.15/qt5.15/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/zx/qt5.15/qt5.15/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = IKUNPlayer1.0.0
DISTDIR = /Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/build/release/obj/IKUNPlayer1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/zx/qt5.15/qt5.15/lib
LIBS          = $(SUBLIBS) -F/Users/zx/qt5.15/qt5.15/lib -L/Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/IKUNPlayer/mpv/ -lmpv.2 -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtQml -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ../build/release/obj/

####### Files

SOURCES       = comnetwork.cpp \
		getdouyu.cpp \
		gethuya.cpp \
		getrealurl.cpp \
		main.cpp \
		mainwindow.cpp \
		mpvplayerwidget.cpp ../build/release/moc/moc_comnetwork.cpp \
		../build/release/moc/moc_getdouyu.cpp \
		../build/release/moc/moc_gethuya.cpp \
		../build/release/moc/moc_getrealurl.cpp \
		../build/release/moc/moc_mainwindow.cpp \
		../build/release/moc/moc_mpvplayerwidget.cpp
OBJECTS       = ../build/release/obj/comnetwork.o \
		../build/release/obj/getdouyu.o \
		../build/release/obj/gethuya.o \
		../build/release/obj/getrealurl.o \
		../build/release/obj/main.o \
		../build/release/obj/mainwindow.o \
		../build/release/obj/mpvplayerwidget.o \
		../build/release/obj/moc_comnetwork.o \
		../build/release/obj/moc_getdouyu.o \
		../build/release/obj/moc_gethuya.o \
		../build/release/obj/moc_getrealurl.o \
		../build/release/obj/moc_mainwindow.o \
		../build/release/obj/moc_mpvplayerwidget.o
DIST          = ../../../qt5.15/qt5.15/mkspecs/features/spec_pre.prf \
		../../../qt5.15/qt5.15/mkspecs/qdevice.pri \
		../../../qt5.15/qt5.15/mkspecs/features/device_config.prf \
		../../../qt5.15/qt5.15/mkspecs/common/unix.conf \
		../../../qt5.15/qt5.15/mkspecs/common/mac.conf \
		../../../qt5.15/qt5.15/mkspecs/common/macx.conf \
		../../../qt5.15/qt5.15/mkspecs/common/sanitize.conf \
		../../../qt5.15/qt5.15/mkspecs/common/gcc-base.conf \
		../../../qt5.15/qt5.15/mkspecs/common/gcc-base-mac.conf \
		../../../qt5.15/qt5.15/mkspecs/common/clang.conf \
		../../../qt5.15/qt5.15/mkspecs/common/clang-mac.conf \
		../../../qt5.15/qt5.15/mkspecs/qconfig.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_ext_freetype.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_ext_libpng.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_charts.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_charts_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_concurrent.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_core.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_core_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_dbus.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_designer.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_designer_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_gamepad.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_gui.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_gui_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_help.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_help_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_location.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_location_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_macextras.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_multimedia.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_network.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_network_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_networkauth.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_nfc.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_opengl.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_positioning.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_printsupport.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_purchasing.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qml.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qml_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmltest.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3d.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_repparser.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_script.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_script_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_scripttools.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_scxml.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_sensors.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_serialbus.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_serialport.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_sql.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_sql_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_svg.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_svg_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_testlib.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_uitools.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_webchannel.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_websockets.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_webview.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_webview_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_widgets.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_xml.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_xml_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../qt5.15/qt5.15/mkspecs/features/qt_functions.prf \
		../../../qt5.15/qt5.15/mkspecs/features/qt_config.prf \
		../../../qt5.15/qt5.15/mkspecs/macx-clang/qmake.conf \
		../../../qt5.15/qt5.15/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../qt5.15/qt5.15/mkspecs/features/exclusive_builds.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/sdk.prf \
		../../../qt5.15/qt5.15/mkspecs/features/toolchain.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/toolchain.prf \
		../../../qt5.15/qt5.15/mkspecs/features/default_pre.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/default_pre.prf \
		../../../qt5.15/qt5.15/mkspecs/features/resolve_config.prf \
		../../../qt5.15/qt5.15/mkspecs/features/default_post.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/default_post.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/objective_c.prf \
		../../../qt5.15/qt5.15/mkspecs/features/resources_functions.prf \
		../../../qt5.15/qt5.15/mkspecs/features/qtquickcompiler.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/mac.prf \
		../../../qt5.15/qt5.15/mkspecs/features/warn_on.prf \
		../../../qt5.15/qt5.15/mkspecs/features/qt.prf \
		../../../qt5.15/qt5.15/mkspecs/features/resources.prf \
		../../../qt5.15/qt5.15/mkspecs/features/moc.prf \
		../../../qt5.15/qt5.15/mkspecs/features/unix/opengl.prf \
		../../../qt5.15/qt5.15/mkspecs/features/uic.prf \
		../../../qt5.15/qt5.15/mkspecs/features/unix/thread.prf \
		../../../qt5.15/qt5.15/mkspecs/features/qmake_use.prf \
		../../../qt5.15/qt5.15/mkspecs/features/file_copies.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/rez.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/asset_catalogs.prf \
		../../../qt5.15/qt5.15/mkspecs/features/testcase_targets.prf \
		../../../qt5.15/qt5.15/mkspecs/features/exceptions.prf \
		../../../qt5.15/qt5.15/mkspecs/features/yacc.prf \
		../../../qt5.15/qt5.15/mkspecs/features/lex.prf \
		IKUNPlayer.pro comnetwork.h \
		getdouyu.h \
		gethuya.h \
		getrealurl.h \
		mainwindow.h \
		mpvplayerwidget.h comnetwork.cpp \
		getdouyu.cpp \
		gethuya.cpp \
		getrealurl.cpp \
		main.cpp \
		mainwindow.cpp \
		mpvplayerwidget.cpp
QMAKE_TARGET  = IKUNPlayer
DESTDIR       = ../bin/release/
TARGET        = ../bin/release/IKUNPlayer.app/Contents/MacOS/IKUNPlayer

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 13.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/IKUNPlayer/.qmake.stash
EXPORT_VALID_ARCHS = arm64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/IKUNPlayer/IKUNPlayer.pro


include /Users/zx/qt5.15/qt5.15/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

../bin/release/IKUNPlayer.app/Contents/MacOS/IKUNPlayer: ../build/release/ui/ui_mainwindow.h ../build/release/ui/ui_mpvplayerwidget.h $(OBJECTS)  
	@test -d ../bin/release/IKUNPlayer.app/Contents/MacOS/ || mkdir -p ../bin/release/IKUNPlayer.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: IKUNPlayer.pro ../../../qt5.15/qt5.15/mkspecs/macx-clang/qmake.conf ../../../qt5.15/qt5.15/mkspecs/features/spec_pre.prf \
		../../../qt5.15/qt5.15/mkspecs/qdevice.pri \
		../../../qt5.15/qt5.15/mkspecs/features/device_config.prf \
		../../../qt5.15/qt5.15/mkspecs/common/unix.conf \
		../../../qt5.15/qt5.15/mkspecs/common/mac.conf \
		../../../qt5.15/qt5.15/mkspecs/common/macx.conf \
		../../../qt5.15/qt5.15/mkspecs/common/sanitize.conf \
		../../../qt5.15/qt5.15/mkspecs/common/gcc-base.conf \
		../../../qt5.15/qt5.15/mkspecs/common/gcc-base-mac.conf \
		../../../qt5.15/qt5.15/mkspecs/common/clang.conf \
		../../../qt5.15/qt5.15/mkspecs/common/clang-mac.conf \
		../../../qt5.15/qt5.15/mkspecs/qconfig.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_ext_freetype.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_ext_libpng.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_charts.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_charts_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_concurrent.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_core.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_core_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_dbus.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_designer.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_designer_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_gamepad.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_gui.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_gui_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_help.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_help_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_location.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_location_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_macextras.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_multimedia.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_network.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_network_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_networkauth.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_nfc.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_opengl.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_positioning.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_printsupport.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_purchasing.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qml.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qml_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmltest.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3d.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_repparser.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_script.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_script_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_scripttools.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_scxml.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_sensors.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_serialbus.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_serialport.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_sql.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_sql_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_svg.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_svg_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_testlib.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_uitools.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_webchannel.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_websockets.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_webview.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_webview_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_widgets.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_xml.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_xml_private.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../qt5.15/qt5.15/mkspecs/features/qt_functions.prf \
		../../../qt5.15/qt5.15/mkspecs/features/qt_config.prf \
		../../../qt5.15/qt5.15/mkspecs/macx-clang/qmake.conf \
		../../../qt5.15/qt5.15/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../qt5.15/qt5.15/mkspecs/features/exclusive_builds.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/sdk.prf \
		../../../qt5.15/qt5.15/mkspecs/features/toolchain.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/toolchain.prf \
		../../../qt5.15/qt5.15/mkspecs/features/default_pre.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/default_pre.prf \
		../../../qt5.15/qt5.15/mkspecs/features/resolve_config.prf \
		../../../qt5.15/qt5.15/mkspecs/features/default_post.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/default_post.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/objective_c.prf \
		../../../qt5.15/qt5.15/mkspecs/features/resources_functions.prf \
		../../../qt5.15/qt5.15/mkspecs/features/qtquickcompiler.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/mac.prf \
		../../../qt5.15/qt5.15/mkspecs/features/warn_on.prf \
		../../../qt5.15/qt5.15/mkspecs/features/qt.prf \
		../../../qt5.15/qt5.15/mkspecs/features/resources.prf \
		../../../qt5.15/qt5.15/mkspecs/features/moc.prf \
		../../../qt5.15/qt5.15/mkspecs/features/unix/opengl.prf \
		../../../qt5.15/qt5.15/mkspecs/features/uic.prf \
		../../../qt5.15/qt5.15/mkspecs/features/unix/thread.prf \
		../../../qt5.15/qt5.15/mkspecs/features/qmake_use.prf \
		../../../qt5.15/qt5.15/mkspecs/features/file_copies.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/rez.prf \
		../../../qt5.15/qt5.15/mkspecs/features/mac/asset_catalogs.prf \
		../../../qt5.15/qt5.15/mkspecs/features/testcase_targets.prf \
		../../../qt5.15/qt5.15/mkspecs/features/exceptions.prf \
		../../../qt5.15/qt5.15/mkspecs/features/yacc.prf \
		../../../qt5.15/qt5.15/mkspecs/features/lex.prf \
		IKUNPlayer.pro \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Resources/QtGui.prl \
		../../../qt5.15/qt5.15/lib/QtQml.framework/Resources/QtQml.prl \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile IKUNPlayer.pro -spec macx-clang CONFIG+=release CONFIG+=qtquickcompiler
../../../qt5.15/qt5.15/mkspecs/features/spec_pre.prf:
../../../qt5.15/qt5.15/mkspecs/qdevice.pri:
../../../qt5.15/qt5.15/mkspecs/features/device_config.prf:
../../../qt5.15/qt5.15/mkspecs/common/unix.conf:
../../../qt5.15/qt5.15/mkspecs/common/mac.conf:
../../../qt5.15/qt5.15/mkspecs/common/macx.conf:
../../../qt5.15/qt5.15/mkspecs/common/sanitize.conf:
../../../qt5.15/qt5.15/mkspecs/common/gcc-base.conf:
../../../qt5.15/qt5.15/mkspecs/common/gcc-base-mac.conf:
../../../qt5.15/qt5.15/mkspecs/common/clang.conf:
../../../qt5.15/qt5.15/mkspecs/common/clang-mac.conf:
../../../qt5.15/qt5.15/mkspecs/qconfig.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_ext_freetype.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_ext_libjpeg.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_ext_libpng.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_bluetooth.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_charts.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_charts_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_concurrent.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_core.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_core_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_datavisualization.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_dbus.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_dbus_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_designer.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_designer_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_gamepad.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_gui.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_gui_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_help.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_help_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_location.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_location_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_macextras.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_macextras_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_multimedia.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_network.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_network_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_networkauth.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_nfc.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_nfc_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_opengl.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_opengl_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_openglextensions.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_positioning.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_positioning_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_positioningquick.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_printsupport.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_purchasing.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qml.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qml_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmltest.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3d.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3d_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3drender.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3dutils.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quick_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_repparser.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_repparser_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_script.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_script_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_scripttools.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_scxml.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_scxml_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_sensors.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_sensors_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_serialbus.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_serialport.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_serialport_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_service_support_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_sql.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_sql_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_svg.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_svg_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_testlib.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_testlib_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_texttospeech.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_uiplugin.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_uitools.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_uitools_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_webchannel.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_websockets.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_websockets_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_webview.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_webview_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_widgets.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_widgets_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_xml.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_xml_private.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../qt5.15/qt5.15/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../qt5.15/qt5.15/mkspecs/features/qt_functions.prf:
../../../qt5.15/qt5.15/mkspecs/features/qt_config.prf:
../../../qt5.15/qt5.15/mkspecs/macx-clang/qmake.conf:
../../../qt5.15/qt5.15/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../qt5.15/qt5.15/mkspecs/features/exclusive_builds.prf:
../../../qt5.15/qt5.15/mkspecs/features/mac/sdk.prf:
../../../qt5.15/qt5.15/mkspecs/features/toolchain.prf:
../../../qt5.15/qt5.15/mkspecs/features/mac/toolchain.prf:
../../../qt5.15/qt5.15/mkspecs/features/default_pre.prf:
../../../qt5.15/qt5.15/mkspecs/features/mac/default_pre.prf:
../../../qt5.15/qt5.15/mkspecs/features/resolve_config.prf:
../../../qt5.15/qt5.15/mkspecs/features/default_post.prf:
../../../qt5.15/qt5.15/mkspecs/features/mac/default_post.prf:
../../../qt5.15/qt5.15/mkspecs/features/mac/objective_c.prf:
../../../qt5.15/qt5.15/mkspecs/features/resources_functions.prf:
../../../qt5.15/qt5.15/mkspecs/features/qtquickcompiler.prf:
../../../qt5.15/qt5.15/mkspecs/features/mac/mac.prf:
../../../qt5.15/qt5.15/mkspecs/features/warn_on.prf:
../../../qt5.15/qt5.15/mkspecs/features/qt.prf:
../../../qt5.15/qt5.15/mkspecs/features/resources.prf:
../../../qt5.15/qt5.15/mkspecs/features/moc.prf:
../../../qt5.15/qt5.15/mkspecs/features/unix/opengl.prf:
../../../qt5.15/qt5.15/mkspecs/features/uic.prf:
../../../qt5.15/qt5.15/mkspecs/features/unix/thread.prf:
../../../qt5.15/qt5.15/mkspecs/features/qmake_use.prf:
../../../qt5.15/qt5.15/mkspecs/features/file_copies.prf:
../../../qt5.15/qt5.15/mkspecs/features/mac/rez.prf:
../../../qt5.15/qt5.15/mkspecs/features/mac/asset_catalogs.prf:
../../../qt5.15/qt5.15/mkspecs/features/testcase_targets.prf:
../../../qt5.15/qt5.15/mkspecs/features/exceptions.prf:
../../../qt5.15/qt5.15/mkspecs/features/yacc.prf:
../../../qt5.15/qt5.15/mkspecs/features/lex.prf:
IKUNPlayer.pro:
../../../qt5.15/qt5.15/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../qt5.15/qt5.15/lib/QtGui.framework/Resources/QtGui.prl:
../../../qt5.15/qt5.15/lib/QtQml.framework/Resources/QtQml.prl:
../../../qt5.15/qt5.15/lib/QtNetwork.framework/Resources/QtNetwork.prl:
../../../qt5.15/qt5.15/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile IKUNPlayer.pro -spec macx-clang CONFIG+=release CONFIG+=qtquickcompiler

qmake_all: FORCE

../bin/release/IKUNPlayer.app/Contents/PkgInfo: 
	@test -d ../bin/release/IKUNPlayer.app/Contents || mkdir -p ../bin/release/IKUNPlayer.app/Contents
	@$(DEL_FILE) ../bin/release/IKUNPlayer.app/Contents/PkgInfo
	@echo "APPL????" > ../bin/release/IKUNPlayer.app/Contents/PkgInfo
../bin/release/IKUNPlayer.app/Contents/Resources/empty.lproj: 
	@test -d ../bin/release/IKUNPlayer.app/Contents/Resources || mkdir -p ../bin/release/IKUNPlayer.app/Contents/Resources
	@touch ../bin/release/IKUNPlayer.app/Contents/Resources/empty.lproj
	
../bin/release/IKUNPlayer.app/Contents/Info.plist: 
	@test -d ../bin/release/IKUNPlayer.app/Contents || mkdir -p ../bin/release/IKUNPlayer.app/Contents
	@$(DEL_FILE) ../bin/release/IKUNPlayer.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.IKUNPlayer,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.IKUNPlayer,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,logo.icns,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},logo.icns,g" -e "s,@EXECUTABLE@,IKUNPlayer,g" -e "s,@LIBRARY@,IKUNPlayer,g" -e "s,\$${EXECUTABLE_NAME},IKUNPlayer,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../../qt5.15/qt5.15/mkspecs/macx-clang/Info.plist.app >../bin/release/IKUNPlayer.app/Contents/Info.plist
../bin/release/IKUNPlayer.app/Contents/Resources/logo.icns: logo.icns
	@test -d ../bin/release/IKUNPlayer.app/Contents/Resources/ || mkdir -p ../bin/release/IKUNPlayer.app/Contents/Resources/
	@$(DEL_FILE) ../bin/release/IKUNPlayer.app/Contents/Resources/logo.icns
	@$(COPY_FILE) logo.icns ../bin/release/IKUNPlayer.app/Contents/Resources/logo.icns

all: Makefile \
		../bin/release/IKUNPlayer.app/Contents/PkgInfo \
		../bin/release/IKUNPlayer.app/Contents/Resources/empty.lproj \
		../bin/release/IKUNPlayer.app/Contents/Info.plist \
		../bin/release/IKUNPlayer.app/Contents/Resources/logo.icns ../bin/release/IKUNPlayer.app/Contents/MacOS/IKUNPlayer

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../qt5.15/qt5.15/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents comnetwork.h getdouyu.h gethuya.h getrealurl.h mainwindow.h mpvplayerwidget.h $(DISTDIR)/
	$(COPY_FILE) --parents comnetwork.cpp getdouyu.cpp gethuya.cpp getrealurl.cpp main.cpp mainwindow.cpp mpvplayerwidget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui mpvplayerwidget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r ../bin/release/IKUNPlayer.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=release CONFIG+=qtquickcompiler

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_qmlcache_make_all:
compiler_qmlcache_clean:
compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: ../build/release/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) ../build/release/moc/moc_predefs.h
../build/release/moc/moc_predefs.h: ../../../qt5.15/qt5.15/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o ../build/release/moc/moc_predefs.h ../../../qt5.15/qt5.15/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: ../build/release/moc/moc_comnetwork.cpp ../build/release/moc/moc_getdouyu.cpp ../build/release/moc/moc_gethuya.cpp ../build/release/moc/moc_getrealurl.cpp ../build/release/moc/moc_mainwindow.cpp ../build/release/moc/moc_mpvplayerwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) ../build/release/moc/moc_comnetwork.cpp ../build/release/moc/moc_getdouyu.cpp ../build/release/moc/moc_gethuya.cpp ../build/release/moc/moc_getrealurl.cpp ../build/release/moc/moc_mainwindow.cpp ../build/release/moc/moc_mpvplayerwidget.cpp
../build/release/moc/moc_comnetwork.cpp: comnetwork.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qobject.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QEventLoop \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qeventloop.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QRegExp \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qregexp.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonDocument \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonArray \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QDebug \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qdebug.h \
		../build/release/moc/moc_predefs.h \
		../../../qt5.15/qt5.15/bin/moc
	/Users/zx/qt5.15/qt5.15/bin/moc $(DEFINES) --include /Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/build/release/moc/moc_predefs.h -I/Users/zx/qt5.15/qt5.15/mkspecs/macx-clang -I/Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/IKUNPlayer -I/Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/IKUNPlayer/mpv/include -I/Users/zx/qt5.15/qt5.15/lib/QtWidgets.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtGui.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtQml.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtNetwork.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/zx/qt5.15/qt5.15/lib comnetwork.h -o ../build/release/moc/moc_comnetwork.cpp

../build/release/moc/moc_getdouyu.cpp: getdouyu.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qobject.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonArray \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QRunnable \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qrunnable.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonobject.h \
		../build/release/moc/moc_predefs.h \
		../../../qt5.15/qt5.15/bin/moc
	/Users/zx/qt5.15/qt5.15/bin/moc $(DEFINES) --include /Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/build/release/moc/moc_predefs.h -I/Users/zx/qt5.15/qt5.15/mkspecs/macx-clang -I/Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/IKUNPlayer -I/Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/IKUNPlayer/mpv/include -I/Users/zx/qt5.15/qt5.15/lib/QtWidgets.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtGui.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtQml.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtNetwork.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/zx/qt5.15/qt5.15/lib getdouyu.h -o ../build/release/moc/moc_getdouyu.cpp

../build/release/moc/moc_gethuya.cpp: gethuya.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qobject.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QRunnable \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qrunnable.h \
		../build/release/moc/moc_predefs.h \
		../../../qt5.15/qt5.15/bin/moc
	/Users/zx/qt5.15/qt5.15/bin/moc $(DEFINES) --include /Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/build/release/moc/moc_predefs.h -I/Users/zx/qt5.15/qt5.15/mkspecs/macx-clang -I/Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/IKUNPlayer -I/Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/IKUNPlayer/mpv/include -I/Users/zx/qt5.15/qt5.15/lib/QtWidgets.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtGui.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtQml.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtNetwork.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/zx/qt5.15/qt5.15/lib gethuya.h -o ../build/release/moc/moc_gethuya.cpp

../build/release/moc/moc_getrealurl.cpp: getrealurl.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qobject.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonobject.h \
		gethuya.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QRunnable \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qrunnable.h \
		getdouyu.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonArray \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonarray.h \
		../build/release/moc/moc_predefs.h \
		../../../qt5.15/qt5.15/bin/moc
	/Users/zx/qt5.15/qt5.15/bin/moc $(DEFINES) --include /Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/build/release/moc/moc_predefs.h -I/Users/zx/qt5.15/qt5.15/mkspecs/macx-clang -I/Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/IKUNPlayer -I/Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/IKUNPlayer/mpv/include -I/Users/zx/qt5.15/qt5.15/lib/QtWidgets.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtGui.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtQml.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtNetwork.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/zx/qt5.15/qt5.15/lib getrealurl.h -o ../build/release/moc/moc_getrealurl.cpp

../build/release/moc/moc_mainwindow.cpp: mainwindow.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QListWidgetItem \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qobject.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Headers/QMouseEvent \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Headers/qevent.h \
		getdouyu.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonArray \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QRunnable \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qrunnable.h \
		gethuya.h \
		mpvplayerwidget.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QWidget \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QDebug \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qdebug.h \
		mpv/include/client.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QTimer \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qtimer.h \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Headers/QKeyEvent \
		getrealurl.h \
		../build/release/moc/moc_predefs.h \
		../../../qt5.15/qt5.15/bin/moc
	/Users/zx/qt5.15/qt5.15/bin/moc $(DEFINES) --include /Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/build/release/moc/moc_predefs.h -I/Users/zx/qt5.15/qt5.15/mkspecs/macx-clang -I/Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/IKUNPlayer -I/Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/IKUNPlayer/mpv/include -I/Users/zx/qt5.15/qt5.15/lib/QtWidgets.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtGui.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtQml.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtNetwork.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/zx/qt5.15/qt5.15/lib mainwindow.h -o ../build/release/moc/moc_mainwindow.cpp

../build/release/moc/moc_mpvplayerwidget.cpp: mpvplayerwidget.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QWidget \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qobject.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QDebug \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qdebug.h \
		mpv/include/client.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QTimer \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qtimer.h \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Headers/QKeyEvent \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Headers/qevent.h \
		../build/release/moc/moc_predefs.h \
		../../../qt5.15/qt5.15/bin/moc
	/Users/zx/qt5.15/qt5.15/bin/moc $(DEFINES) --include /Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/build/release/moc/moc_predefs.h -I/Users/zx/qt5.15/qt5.15/mkspecs/macx-clang -I/Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/IKUNPlayer -I/Users/zx/qtWorkspace/QtAppProject-mpvDemoModify/IKUNPlayer/mpv/include -I/Users/zx/qt5.15/qt5.15/lib/QtWidgets.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtGui.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtQml.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtNetwork.framework/Headers -I/Users/zx/qt5.15/qt5.15/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/zx/qt5.15/qt5.15/lib mpvplayerwidget.h -o ../build/release/moc/moc_mpvplayerwidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ../build/release/ui/ui_mainwindow.h ../build/release/ui/ui_mpvplayerwidget.h
compiler_uic_clean:
	-$(DEL_FILE) ../build/release/ui/ui_mainwindow.h ../build/release/ui/ui_mpvplayerwidget.h
../build/release/ui/ui_mainwindow.h: mainwindow.ui \
		../../../qt5.15/qt5.15/bin/uic \
		mpvplayerwidget.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QWidget \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qobject.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QDebug \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qdebug.h \
		mpv/include/client.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QTimer \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qtimer.h \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Headers/QKeyEvent \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Headers/qevent.h
	/Users/zx/qt5.15/qt5.15/bin/uic mainwindow.ui -o ../build/release/ui/ui_mainwindow.h

../build/release/ui/ui_mpvplayerwidget.h: mpvplayerwidget.ui \
		../../../qt5.15/qt5.15/bin/uic
	/Users/zx/qt5.15/qt5.15/bin/uic mpvplayerwidget.ui -o ../build/release/ui/ui_mpvplayerwidget.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

../build/release/obj/comnetwork.o: comnetwork.cpp comnetwork.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qobject.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QEventLoop \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qeventloop.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QRegExp \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qregexp.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonDocument \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonArray \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QDebug \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/release/obj/comnetwork.o comnetwork.cpp

../build/release/obj/getdouyu.o: getdouyu.cpp getdouyu.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qobject.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonArray \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QRunnable \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qrunnable.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonobject.h \
		comnetwork.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QEventLoop \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qeventloop.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QRegExp \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qregexp.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonDocument \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QDebug \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qdebug.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QDateTime \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qdatetime.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QUrl \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qurl.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QTextCodec \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qtextcodec.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QCryptographicHash \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qcryptographichash.h \
		../../../qt5.15/qt5.15/lib/QtQml.framework/Headers/QJSEngine \
		../../../qt5.15/qt5.15/lib/QtQml.framework/Headers/qjsengine.h \
		../../../qt5.15/qt5.15/lib/QtQml.framework/Headers/QJSValueList \
		../../../qt5.15/qt5.15/lib/QtQml.framework/Headers/qjsvalue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/release/obj/getdouyu.o getdouyu.cpp

../build/release/obj/gethuya.o: gethuya.cpp gethuya.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qobject.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QRunnable \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qrunnable.h \
		comnetwork.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QEventLoop \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qeventloop.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QRegExp \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qregexp.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonDocument \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonArray \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QDebug \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qdebug.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QDateTime \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qdatetime.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QSslSocket \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qsslsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/release/obj/gethuya.o gethuya.cpp

../build/release/obj/getrealurl.o: getrealurl.cpp getrealurl.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qobject.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonobject.h \
		gethuya.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QRunnable \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qrunnable.h \
		getdouyu.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonArray \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QApplication \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QFile \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qfile.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QIODevice \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qiodevice.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QThreadPool \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qthreadpool.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QThread \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/release/obj/getrealurl.o getrealurl.cpp

../build/release/obj/main.o: main.cpp mainwindow.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QListWidgetItem \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qobject.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Headers/QMouseEvent \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Headers/qevent.h \
		getdouyu.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonArray \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QRunnable \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qrunnable.h \
		gethuya.h \
		mpvplayerwidget.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QWidget \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QDebug \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qdebug.h \
		mpv/include/client.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QTimer \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qtimer.h \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Headers/QKeyEvent \
		getrealurl.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QApplication \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/release/obj/main.o main.cpp

../build/release/obj/mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QListWidgetItem \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qobject.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Headers/QMouseEvent \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Headers/qevent.h \
		getdouyu.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../qt5.15/qt5.15/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QJsonArray \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QRunnable \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qrunnable.h \
		gethuya.h \
		mpvplayerwidget.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QWidget \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QDebug \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qdebug.h \
		mpv/include/client.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QTimer \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qtimer.h \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Headers/QKeyEvent \
		getrealurl.h \
		../build/release/ui/ui_mainwindow.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QList \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qlist.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QApplication \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QFile \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qfile.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QTextStream \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qtextstream.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QThreadPool \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qthreadpool.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QThread \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/release/obj/mainwindow.o mainwindow.cpp

../build/release/obj/mpvplayerwidget.o: mpvplayerwidget.cpp mpvplayerwidget.h \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/QWidget \
		../../../qt5.15/qt5.15/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QObject \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qobject.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QDebug \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qdebug.h \
		mpv/include/client.h \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/QTimer \
		../../../qt5.15/qt5.15/lib/QtCore.framework/Headers/qtimer.h \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Headers/QKeyEvent \
		../../../qt5.15/qt5.15/lib/QtGui.framework/Headers/qevent.h \
		../build/release/ui/ui_mpvplayerwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/release/obj/mpvplayerwidget.o mpvplayerwidget.cpp

../build/release/obj/moc_comnetwork.o: ../build/release/moc/moc_comnetwork.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/release/obj/moc_comnetwork.o ../build/release/moc/moc_comnetwork.cpp

../build/release/obj/moc_getdouyu.o: ../build/release/moc/moc_getdouyu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/release/obj/moc_getdouyu.o ../build/release/moc/moc_getdouyu.cpp

../build/release/obj/moc_gethuya.o: ../build/release/moc/moc_gethuya.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/release/obj/moc_gethuya.o ../build/release/moc/moc_gethuya.cpp

../build/release/obj/moc_getrealurl.o: ../build/release/moc/moc_getrealurl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/release/obj/moc_getrealurl.o ../build/release/moc/moc_getrealurl.cpp

../build/release/obj/moc_mainwindow.o: ../build/release/moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/release/obj/moc_mainwindow.o ../build/release/moc/moc_mainwindow.cpp

../build/release/obj/moc_mpvplayerwidget.o: ../build/release/moc/moc_mpvplayerwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../build/release/obj/moc_mpvplayerwidget.o ../build/release/moc/moc_mpvplayerwidget.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/IKUNPlayer/bin || mkdir -p $(INSTALL_ROOT)/opt/IKUNPlayer/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/IKUNPlayer/bin/IKUNPlayer.app
	
	$(QINSTALL) ../bin/release/IKUNPlayer.app $(INSTALL_ROOT)/opt/IKUNPlayer/bin/IKUNPlayer.app
	-$(STRIP) $(INSTALL_ROOT)/opt/IKUNPlayer/bin/IKUNPlayer.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/IKUNPlayer/bin/IKUNPlayer.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/IKUNPlayer/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

