name: Makefile CI

on:
  push:
    branches: [ "main" , "dev"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: choco install -y qt5-default --version=5.15.2.20230429
       
    - name: qmake
      run: |
        C:\Qt\5.15.2\mingw81_64\bin\qmake.exe IKUNPlayer.pro
        make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
