name: Makefile CI

on:
  push:
      tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:

    - uses: actions/checkout@v3
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw81'
        modules: 'debug_info qtcharts qtdatavis3d qtlottie qtnetworkauth qtpurchasing qtquick3d qtquicktimeline qtscript qtvirtualkeyboard qtwebglplugin'
       
    - name: qmake
      run:  qmake IKUNPlayer.pro
        
    - name: build
      run: make
        
    - name: packing
      run: windeployqt bin/release/iKunPlayer.exe

    - name: upload-build
      uses: actions/upload-artifact@v3
      with:
        name: iKunPlayer_win_x64
        path: bin/release/
        
    - name: download
      uses: actions/download-artifact@v3
      with:
         name: iKunPlayer_win_x64
         
    - name: Create a Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "iKunPlayer_win_x64*"
  
